/** Canonical content. Breath of Innovation · July 8, 2026 */
window.BOI = {
  event: {
    title: "Breath of Innovation",
    date: "Tuesday, July 8, 2026",
    location: "Norco, California",
    arrival: "9:00 AM",
    arrivalNote: "2058 Second Street, facility tour at 9:00 AM, presentation across the street at 9:30",
    facility: "2058 Second Street, Norco, CA 92860",
    phone: "(951) 273-9877",
    web: "flavorfactory.net",
  },
  schedule: [
    { time: "9:00 AM", end: "9:25", title: "Facility tour", desc: "Production, QC, TheraBreath room", accent: "#5fb832" },
    { time: "9:30", end: "10:15", title: "Presentation", desc: "Four pillars, open conversation", accent: "#008fd3" },
    { time: "10:15", end: "10:30", title: "Break", desc: "Reset before tasting", accent: "#5c6678" },
    { time: "10:30", end: "11:15", title: "Tasting", desc: "Five prototypes · blind then score", accent: "#f58220" },
    { time: "11:30", end: "1:00", title: "Lunch off site", desc: "Your hosts take the group", accent: "#5b6b8a" },
    { time: "1:00 PM+", end: "", title: "Open Q&A", desc: "Your topics · your pace", accent: "#006da3" },
    { time: "5:00 PM", end: "", title: "Dinner", desc: "Evening with your hosts", accent: "#9028ab" },
  ],
  pillars: [
    {
      id: "resiliency",
      num: 1,
      title: "Resiliency",
      tagline: "Protect the core as you grow.",
      color: "#008fd3",
      points: ["Capacity & growth scenarios", "SQF · GMP · FDA registered", "Alternate suppliers & continuity"],
    },
    {
      id: "innovation",
      num: 2,
      title: "Innovation",
      tagline: "Flavor work inside your products.",
      color: "#5fb832",
      points: ["Oral-care & chlorite chemistry", "Sensory science & prototypes", "Competitive & seasonal directions"],
    },
    {
      id: "operations",
      num: 3,
      title: "Operations",
      tagline: "One roof. Full visibility.",
      color: "#f58220",
      points: ["Norco dev + production + QC", "Batch release & traceability", "COAs & supplier documentation"],
    },
    {
      id: "partnership",
      num: 4,
      title: "Partnership",
      tagline: "Build together long term.",
      color: "#0a1628",
      points: ["Communication cadence", "Investment alignment", "Co-development roadmap"],
    },
  ],
  qaSections: [
    {
      pillar: "Resiliency & Business Continuity",
      pillarShort: "Pillar 1",
      num: 1,
      color: "#008fd3",
      intro: "Supply security, capacity, and continuity as TheraBreath grows.",
      questionTitle: "Can we scale with you and absorb a shock?",
      discussion: "When has a flavor supplier let you down, and what did it cost you?",
      cards: [
        {
          num: 1,
          question: "If your volume doubles over the next 3 to 5 years, how do we support that growth?",
          points: ["Built for headroom", "More shifts & equipment", "Invest as you grow"],
          answer: "Growth is a good problem to have. Our job is making sure flavor never becomes the bottleneck. We've built room into our people, our processes, and our facility so we can grow alongside you.",
        },
        {
          num: 2,
          question: "What happens if one of our key suppliers goes down?",
          points: ["Secondary sources", "Critical inventory", "PG shortage lessons"],
          answer: "The PG shortage taught everybody in this industry some lessons. Ours was simple: don't wait for the disruption to start planning for the disruption. That's changed how we think about inventory and secondary sourcing.",
        },
        {
          num: 3,
          question: "What happens if one of our key people is out?",
          points: ["Cross-trained team", "No single point of failure", "Continuity by design"],
          answer: "Cross-training is a major focus at The Flavor Factory. Multiple team members are trained across production, warehousing, shipping, receiving, and quality functions. This reduces dependence on any one individual and helps ensure operational continuity.",
        },
        {
          num: 4,
          question: "How do we maintain quality as volume grows?",
          points: ["Full traceability", "Batch records", "Same specs, more scale"],
          answer: "Making ten batches right isn't impressive. Making ten thousand batches right is what matters. Traceability and consistency become even more important as volume grows.",
        },
        {
          num: 5,
          question: "How would we respond to a major disruption or disaster?",
          points: ["Contingency plans", "Backup capacity", "Supply continuity"],
          answer: "Stuff happens in manufacturing. Equipment fails. Suppliers fail. Demand spikes happen. The question isn't whether something goes wrong. It's whether you're ready when it does.",
        },
      ],
    },
    {
      pillar: "Innovation & Technical Capabilities",
      pillarShort: "Pillar 2",
      num: 2,
      color: "#5fb832",
      intro: "Flavor development, sensory science, and what's next for oral care.",
      questionTitle: "Where do new flavors actually come from?",
      discussion: "What is the flavor request you have not made yet because you assumed the answer was no?",
      cards: [
        {
          num: 6,
          question: "How do we stay ahead of flavor trends?",
          points: ["We bring ideas to you", "Watch ingredients & consumers", "Proactive, not reactive"],
          answer: "We don't want to wait for the brief. The goal is to bring ideas to your team before the market starts asking for them.",
        },
        {
          num: 7,
          question: "Can we support products beyond today's mouthrinse portfolio?",
          points: ["Kids · gummies · powders", "Wellness & seasonal", "Future adjacencies"],
          answer: "Absolutely. Kids products, wellness, gummies, powders, seasonal launches. If TheraBreath decides to play there, we want to be ready to help build it.",
        },
        {
          num: 8,
          question: "How do we approach innovation?",
          points: ["Fast prototypes", "Your feedback loop", "Bench → production"],
          answer: "We combine creative flavor development with practical manufacturing expertise. Our team rapidly develops prototypes, gathers feedback, refines concepts, and works collaboratively with customers to accelerate innovation.",
        },
        {
          num: 9,
          question: "How do we validate sensory performance?",
          points: ["Triangle testing", "Consumer feedback", "University partners"],
          answer: "Sometimes a formula changes and nobody notices. Sometimes a tiny change becomes a huge consumer issue. Our goal is getting better at understanding that difference before products hit shelves.",
        },
        {
          num: 10,
          question: "What innovation opportunities excite us most for TheraBreath?",
          points: ["Next-gen cooling", "Pediatric & wellness", "Seasonal & longevity"],
          answer: "Honestly? The intersection between oral care and wellness feels wide open right now. Cooling, longevity, functional ingredients, kids products. It feels like we're still early innings.",
        },
      ],
    },
    {
      pillar: "Operations",
      pillarShort: "Pillar 3",
      num: 3,
      color: "#f58220",
      intro: "Investments, service levels, and securing critical materials.",
      questionTitle: "Can you count on every order?",
      discussion: "What would make us the easiest supplier you work with?",
      cards: [
        {
          num: 11,
          question: "What have we already invested to support TheraBreath?",
          points: ["Dedicated TB space", "Warehouse & process", "Quality systems"],
          answer: "As TheraBreath has grown, we've invested right alongside the business. Space, organization, inventory systems, dedicated TheraBreath production areas. We've tried to stay ahead of where demand is going, not react after it gets there.",
        },
        {
          num: 12,
          question: "How do we maintain service levels and lead times?",
          points: ["Proactive scheduling", "Close collaboration", "Flexible + reliable"],
          answer: "Communication solves most supply chain problems before they become supply chain problems.",
        },
        {
          num: 13,
          question: "How do we secure critical raw materials?",
          points: ["Supplier relationships", "Alt sourcing", "Inventory visibility"],
          answer: "Visibility is everything. The earlier you see a problem coming, the more options you have to solve it.",
        },
        {
          num: 17,
          question: "What does our manufacturing footprint look like, and how does it scale across sites?",
          points: ["One site, one roof", "Contingency partners", "Scales in place"],
          answer: "Being under one roof gives us speed. Development, production, quality, leadership, everyone's here. Decisions happen quickly because the people making them are sitting twenty feet away from each other.",
        },
      ],
    },
    {
      pillar: "Partnership & Growth Vision",
      pillarShort: "Pillar 4",
      num: 4,
      color: "#0a1628",
      intro: "Why TFF is the right long-term partner, and what success looks like.",
      questionTitle: "What does year five look like?",
      discussion: "If this partnership doubled, what would have to be true?",
      cards: [
        {
          num: 14,
          question: "Why are we the right long-term partner for TheraBreath?",
          points: ["Responsive & flexible", "Technical depth", "We invest with you"],
          answer: "The easy answer is flexibility. The real answer is ownership. When something matters to TheraBreath, it matters to us too.",
        },
        {
          num: 15,
          question: "What makes working with us different?",
          points: ["Direct to leadership", "Fast decisions", "Trust & transparency"],
          answer: "If something goes sideways, you don't enter a ticket and wait three days. You call us. You get an answer. Usually pretty quickly.",
        },
        {
          num: 16,
          question: "What does success look like over the next 5 years?",
          points: ["Shared growth", "Innovation pipeline", "Resilient partnership"],
          answer: "Five years from now we'd love to look back and say we helped TheraBreath become bigger, faster, and more innovative than it would have been otherwise.",
        },
      ],
    },
  ],
  strategicQuestions: [
    {
      num: 1,
      question: "What does success look like for TheraBreath in 3 to 5 years?",
      points: ["Align investments with brand direction", "Plan capacity & innovation together"],
      why: "Helps us align our investments and capabilities with the brand's future direction.",
    },
    {
      num: 2,
      question: "What are your biggest growth challenges?",
      points: ["Where TFF can help", "Obstacles to solve jointly"],
      why: "Identifies obstacles where TFF can provide support or solutions.",
    },
    {
      num: 3,
      question: "What separates your best suppliers from everyone else?",
      points: ["What great looks like", "Roadmap for partnership"],
      why: "Provides a roadmap for becoming a stronger strategic partner.",
    },
    {
      num: 4,
      question: "How can suppliers better support your resiliency goals?",
      points: ["Continuity expectations", "Supply security priorities"],
      why: "Reveals expectations around continuity planning and supply security.",
    },
    {
      num: 5,
      question: "What innovation opportunities excite you most?",
      points: ["Highest-value R&D focus", "Where to invest next"],
      why: "Focuses future development efforts on the highest-value opportunities.",
    },
    {
      num: 6,
      question: "What oral care trends are currently underappreciated?",
      points: ["Emerging opportunities", "Get ahead of competitors"],
      why: "Helps uncover emerging opportunities before competitors.",
    },
    {
      num: 7,
      question: "What sensory attributes matter most to consumers today?",
      points: ["Consumer priorities", "Guide flavor development"],
      why: "Guides flavor development and product experience decisions.",
    },
    {
      num: 8,
      question: "What could The Flavor Factory do to become an even stronger partner?",
      points: ["Honest feedback welcome", "How we improve"],
      why: "Creates an opportunity for honest feedback and improvement.",
    },
    {
      num: 9,
      question: "How would you like sensory validation data presented?",
      points: ["Actionable format", "Make testing useful"],
      why: "Ensures our testing efforts provide useful and actionable information.",
    },
    {
      num: 10,
      question: "After today's visit, what would make you most confident in our ability to support future growth?",
      points: ["Address remaining concerns", "End on what builds confidence"],
      why: "Reveals any remaining concerns and focuses attention on what matters most.",
    },
  ],
  /* Deck structure shared by the presentation (present.js) and the
     speaker packet (packet.js), so the packet always matches the
     slides exactly. Presentation and packet use this content. Keep
     them synchronized. shortQ maps card.num to the short row question
     shown on the composed pillar slides. appendixCards lists card
     nums that live only in the appendix. */
  deck: {
    shortQ: {
      1: "Volume doubles in 3 to 5 years?",
      2: "A key supplier goes down?",
      3: "A key person is out?",
      4: "Quality at higher volume?",
      5: "A major disruption hits?",
      6: "How do we stay ahead of trends?",
      7: "Beyond today's mouthrinse portfolio?",
      8: "How do we approach innovation?",
      9: "How do we prove sensory performance?",
      10: "What excites us most?",
      11: "What have we already invested?",
      12: "How do we hold service levels?",
      13: "How do we secure critical materials?",
      17: "One site, or many?",
      14: "Why the right long-term partner?",
      15: "What makes working with us different?",
      16: "What does success look like by year five?",
    },
    appendixCards: { 1: [3], 2: [8] },
    stats: [
      {
        section: 2,
        tag: "Pillar 2 · One number",
        color: "#5fb832",
        question: "How many flavors have we put in front of you so far?",
        value: 53,
        suffix: "",
        story: "14 in production, 29 presented concepts, 5 in today's flight, 5 Gen Alpha directions. The bench runs deep.",
      },
      {
        section: 4,
        tag: "Pillar 4 · One number",
        color: "#0a1628",
        question: "How many years of flavor experience set the standards here?",
        value: 40,
        suffix: "+",
        story: "More than 40 years of flavor experience set the standards here, and it still leads from the bench when a project gets complicated.",
      },
    ],
  },
  chapters: null,
  links: {
    therabreath: "/find",
    flavorFactory: "https://www.flavorfactory.net/",
  },
  nav: [
    { href: "/visit", label: "Your day" },
    { href: "/find", label: "Find" },
    { href: "/portfolio", label: "Portfolio" },
    { href: "/taste", label: "Tasting" },
    { href: "/present", label: "Presentation", cta: true },
  ],
};