/** Canonical content — Breath of Innovation · July 8, 2026 */
window.BOI = {
  event: {
    title: "Breath of Innovation",
    date: "Tuesday, July 8, 2026",
    location: "Norco, California",
    arrival: "9:00 AM",
    arrivalNote: "Conference room across from The Flavor Factory",
    facility: "2058 Second Street, Norco, CA 92860",
    phone: "(951) 273-9877",
    web: "flavorfactory.net",
  },
  schedule: [
    { time: "9:00 AM", end: "10:00", title: "Presentation", desc: "Four pillars — open conversation", accent: "#008fd3", icon: "🎤" },
    { time: "10:00", end: "10:15", title: "Facility tour", desc: "Production, QC, TheraBreath room", accent: "#5fb832", icon: "🏭" },
    { time: "10:15", end: "10:30", title: "Break", desc: "Reset before tasting", accent: "#5c6678", icon: "☕" },
    { time: "10:30", end: "11:15", title: "Tasting", desc: "Ten prototypes · blind then score", accent: "#f58220", icon: "🧪" },
    { time: "11:30", end: "1:00", title: "Lunch off site", desc: "Your hosts take the group", accent: "#5b6b8a", icon: "🍽️" },
    { time: "1:00 PM+", end: "", title: "Open Q&A", desc: "Your topics · your pace", accent: "#006da3", icon: "💬" },
  ],
  pillars: [
    { id: "resiliency", num: 1, title: "Resiliency", tagline: "Grow without surprises.", color: "#008fd3", emoji: "🛡️", image: "/assets/companies/tff/facility.jpg" },
    { id: "innovation", num: 2, title: "Innovation", tagline: "Flavor inside your products.", color: "#5fb832", emoji: "💡", image: "/assets/portfolio/spearmint-garden.jpg" },
    { id: "operations", num: 3, title: "Operations", tagline: "One roof. Full visibility.", color: "#f58220", emoji: "⚙️", image: "/assets/companies/tff/therabreath-production-room.jpg" },
    { id: "partnership", num: 4, title: "Partnership", tagline: "Build together.", color: "#6c5ce7", emoji: "🤝", image: "/assets/companies/therabreath/complete-rinse.jpg" },
  ],
  qaSections: [
    {
      pillar: "Resiliency",
      pillarShort: "Pillar 1",
      num: 1,
      color: "#008fd3",
      emoji: "🛡️",
      image: "/assets/companies/tff/facility.jpg",
      intro: "Supply security as you scale.",
      cards: [
        {
          num: 1,
          emoji: "📈",
          image: "/assets/companies/tff/facility.jpg",
          question: "Volume doubles in 3–5 years?",
          hints: ["Built for headroom", "More shifts & equipment", "Invest as you grow"],
          fullAnswer: "We intentionally operate with room to grow. Our infrastructure, staffing, and production planning can absorb significant growth. We expand schedules, add equipment, increase staffing, and keep investing in the facility to support TheraBreath's trajectory.",
        },
        {
          num: 2,
          emoji: "🔗",
          image: "/assets/companies/tff/certifications.png",
          question: "Key supplier unavailable?",
          hints: ["Secondary sources", "Critical inventory", "PG shortage lessons"],
          fullAnswer: "We actively manage supplier relationships and pursue secondary sourcing whenever possible. We maintain inventory visibility on critical materials and learned valuable lessons from recent disruptions, including the propylene glycol shortage. We minimize risk before it becomes a problem.",
        },
        {
          num: 3,
          emoji: "👥",
          image: "/assets/companies/tff/therabreath-production-room.jpg",
          question: "Key person unavailable?",
          hints: ["Cross-trained team", "No single point of failure", "Continuity by design"],
          fullAnswer: "Cross-training is a major focus. Multiple team members are trained across production, warehousing, shipping, receiving, and quality. This reduces dependence on any one individual and helps ensure operational continuity.",
        },
        {
          num: 4,
          emoji: "✅",
          image: "/assets/companies/therabreath/healthy-gums-rinse.jpg",
          question: "Quality at higher volume?",
          hints: ["Full traceability", "Batch records", "Same specs, more scale"],
          fullAnswer: "Every ingredient, batch, and shipment is fully traceable. We maintain documented procedures, batch records, specification management, supplier qualification programs, and quality review processes to ensure consistency regardless of production volume.",
        },
        {
          num: 5,
          emoji: "🆘",
          image: "/assets/companies/therabreath/oxyd8-hero.jpg",
          question: "Major disruption?",
          hints: ["Contingency plans", "Backup capacity", "Supply continuity"],
          fullAnswer: "We maintain contingency plans, emergency manufacturing relationships, supplier redundancy efforts, and inventory controls designed to minimize business interruption and maintain continuity of supply whenever possible.",
        },
      ],
    },
    {
      pillar: "Innovation",
      pillarShort: "Pillar 2",
      num: 2,
      color: "#5fb832",
      emoji: "💡",
      image: "/assets/portfolio/green-tea-fresh.jpg",
      intro: "What's next for flavor & oral care.",
      cards: [
        {
          num: 6,
          emoji: "🔭",
          image: "/assets/portfolio/watermelon-mojito.jpg",
          question: "Staying ahead of trends?",
          hints: ["We bring ideas to you", "Watch ingredients & consumers", "Proactive, not reactive"],
          fullAnswer: "We continuously evaluate emerging flavor trends, ingredient technologies, consumer preferences, and supplier innovations. Our goal is to proactively bring ideas to TheraBreath rather than waiting to be asked.",
        },
        {
          num: 7,
          emoji: "🧃",
          image: "/assets/companies/therabreath/cat-gum-health.jpg",
          question: "Beyond mouthrinse?",
          hints: ["Kids · gummies · powders", "Wellness & seasonal", "Future adjacencies"],
          fullAnswer: "Yes. Our development capabilities extend beyond mouthrinses into children's products, gummies, powders, wellness products, seasonal programs, and future oral care adjacencies.",
        },
        {
          num: 8,
          emoji: "⚡",
          image: "/assets/portfolio/icy-peak-refresh.jpg",
          question: "How do you innovate?",
          hints: ["Fast prototypes", "Your feedback loop", "Bench → production"],
          fullAnswer: "We combine creative flavor development with practical manufacturing expertise. Our team rapidly develops prototypes, gathers feedback, refines concepts, and works collaboratively with customers to accelerate innovation.",
        },
        {
          num: 9,
          emoji: "👃",
          image: "/assets/portfolio/spearmint-garden.jpg",
          question: "Validate sensory how?",
          hints: ["Triangle testing", "Consumer feedback", "University partners"],
          fullAnswer: "We are building structured sensory evaluation capabilities, including external triangle testing, consumer feedback collection, and university partnerships to better understand how consumers perceive product changes and innovations.",
        },
        {
          num: 10,
          emoji: "🚀",
          image: "/assets/portfolio/electric-blue-chill.jpg",
          question: "What excites you most?",
          hints: ["Next-gen cooling", "Pediatric & wellness", "Seasonal & longevity"],
          fullAnswer: "Next-generation cooling systems, natural sweetness enhancement, pediatric oral care, wellness-focused products, seasonal concepts, and long-lasting freshness technologies represent exciting opportunities for future growth.",
        },
      ],
    },
    {
      pillar: "Operations",
      pillarShort: "Pillar 3",
      num: 3,
      color: "#f58220",
      emoji: "⚙️",
      image: "/assets/companies/tff/therabreath-production-room.jpg",
      intro: "How we run day to day.",
      cards: [
        {
          num: 11,
          emoji: "🏗️",
          image: "/assets/companies/therabreath/deep-clean-rinse.png",
          question: "Investments for TheraBreath?",
          hints: ["Dedicated TB space", "Warehouse & process", "Quality systems"],
          fullAnswer: "Recent investments include facility improvements, warehouse organization, dedicated TheraBreath production space, process improvements, inventory controls, and ongoing investments in quality and operational systems.",
        },
        {
          num: 12,
          emoji: "📦",
          image: "/assets/portfolio/cranberry-lime.jpg",
          question: "Service & lead times?",
          hints: ["Proactive scheduling", "Close collaboration", "Flexible + reliable"],
          fullAnswer: "Through proactive production scheduling, inventory management, supplier communication, and close collaboration with customers. Our goal is to remain flexible while maintaining reliable service.",
        },
        {
          num: 13,
          emoji: "🌿",
          image: "/assets/portfolio/cinnamon-mint.jpg",
          question: "Secure raw materials?",
          hints: ["Supplier relationships", "Alt sourcing", "Inventory visibility"],
          fullAnswer: "We actively manage supplier relationships, monitor inventory levels, evaluate alternative sourcing opportunities, and maintain visibility on critical ingredients to reduce supply risk.",
        },
      ],
    },
    {
      pillar: "Partnership",
      pillarShort: "Pillar 4",
      num: 4,
      color: "#6c5ce7",
      emoji: "🤝",
      image: "/assets/companies/therabreath/complete-rinse.jpg",
      intro: "Why us — and where we're headed.",
      cards: [
        {
          num: 14,
          emoji: "⭐",
          image: "/assets/companies/therabreath/dr-katz.png",
          question: "Why TFF long term?",
          hints: ["Responsive & flexible", "Technical depth", "We invest with you"],
          fullAnswer: "Because we combine responsiveness, flexibility, technical expertise, and personal commitment. We genuinely care about the success of the brands we support and are willing to invest alongside our customers.",
        },
        {
          num: 15,
          emoji: "🎯",
          image: "/assets/companies/tff/oral-care.png",
          question: "What makes TFF different?",
          hints: ["Direct to leadership", "Fast decisions", "Trust & transparency"],
          fullAnswer: "Direct access to leadership, fast decision-making, transparency, and a collaborative problem-solving approach. We believe strong partnerships are built on communication and trust.",
        },
        {
          num: 16,
          emoji: "🏆",
          image: "/assets/companies/therabreath/cat-whitening.png",
          question: "Success in 5 years?",
          hints: ["Shared growth", "Innovation pipeline", "Resilient partnership"],
          fullAnswer: "A stronger, more resilient partnership that supports TheraBreath's continued growth through innovation, supply chain excellence, operational reliability, and shared long-term success.",
        },
      ],
    },
  ],
  strategicQuestions: [
    {
      num: 1,
      emoji: "🎯",
      image: "/assets/companies/therabreath/complete-rinse.jpg",
      question: "Success in 3–5 years?",
      hint: "Align our investments",
      fullWhy: "Helps us align our investments and capabilities with the brand's future direction.",
    },
    {
      num: 2,
      emoji: "🧗",
      image: "/assets/companies/therabreath/cat-bad-breath.png",
      question: "Biggest growth challenges?",
      hint: "Where we can help",
      fullWhy: "Identifies obstacles where TFF can provide support or solutions.",
    },
    {
      num: 3,
      emoji: "🏅",
      image: "/assets/companies/therabreath/cat-dry-mouth.png",
      question: "Best suppliers — what separates them?",
      hint: "Our roadmap",
      fullWhy: "Provides a roadmap for becoming a stronger strategic partner.",
    },
    {
      num: 4,
      emoji: "🛡️",
      image: "/assets/portfolio/honey-ginger.jpg",
      question: "Support your resiliency goals?",
      hint: "Your expectations",
      fullWhy: "Reveals expectations around continuity planning and supply security.",
    },
    {
      num: 5,
      emoji: "💡",
      image: "/assets/portfolio/cloud-matcha-mint.jpg",
      question: "Innovation that excites you?",
      hint: "Focus R&D",
      fullWhy: "Focuses future development efforts on the highest-value opportunities.",
    },
    {
      num: 6,
      emoji: "👀",
      image: "/assets/portfolio/y2k-bubblegum-mint.jpg",
      question: "Underappreciated trends?",
      hint: "First-mover edge",
      fullWhy: "Helps uncover emerging opportunities before competitors.",
    },
    {
      num: 7,
      emoji: "👃",
      image: "/assets/portfolio/green-tea-fresh.jpg",
      question: "Sensory attributes that matter?",
      hint: "Flavor direction",
      fullWhy: "Guides flavor development and product experience decisions.",
    },
    {
      num: 8,
      emoji: "💬",
      image: "/assets/portfolio/pomegranate-ginger.jpg",
      question: "Stronger partner — how?",
      hint: "Honest feedback",
      fullWhy: "Creates an opportunity for honest feedback and improvement.",
    },
    {
      num: 9,
      emoji: "📊",
      image: "/assets/qr/score.png",
      question: "Sensory data — how presented?",
      hint: "Actionable format",
      fullWhy: "Ensures our testing efforts provide useful and actionable information.",
    },
    {
      num: 10,
      emoji: "✨",
      image: "/assets/portfolio/strawberry-pineapple.jpg",
      question: "Confidence after today?",
      hint: "Close remaining gaps",
      fullWhy: "Reveals any remaining concerns and focuses attention on what matters most.",
    },
  ],
  chapters: null,
};