/** Canonical content — Breath of Innovation · July 8, 2026 */
window.BOI = {
  event: {
    title: "Breath of Innovation",
    date: "Tuesday, July 8, 2026",
    location: "Norco, California",
    arrival: "9:00 AM",
    arrivalNote: "Conference room across from The Flavor Factory",
    facility: "2058 Second Street, Norco, CA 92860",
    phone: "(951) 273-9877",
    web: "flavorfactory.net",
  },
  schedule: [
    { time: "9:00 AM", end: "10:00", title: "Presentation", desc: "Four pillars — open conversation", accent: "#008fd3", icon: "🎤" },
    { time: "10:00", end: "10:15", title: "Facility tour", desc: "Production, QC, TheraBreath room", accent: "#5fb832", icon: "🏭" },
    { time: "10:15", end: "10:30", title: "Break", desc: "Reset before tasting", accent: "#5c6678", icon: "☕" },
    { time: "10:30", end: "11:15", title: "Tasting", desc: "Ten prototypes · blind then score", accent: "#f58220", icon: "🧪" },
    { time: "11:30", end: "1:00", title: "Lunch off site", desc: "Your hosts take the group", accent: "#5b6b8a", icon: "🍽️" },
    { time: "1:00 PM+", end: "", title: "Open Q&A", desc: "Your topics · your pace", accent: "#006da3", icon: "💬" },
  ],
  pillars: [
    { id: "resiliency", num: 1, title: "Resiliency", tagline: "Grow without surprises.", color: "#008fd3", emoji: "🛡️", image: "/assets/companies/tff/facility.jpg" },
    { id: "innovation", num: 2, title: "Innovation", tagline: "Flavor inside your products.", color: "#5fb832", emoji: "💡", image: "/assets/portfolio/spearmint-garden.jpg" },
    { id: "operations", num: 3, title: "Operations", tagline: "One roof. Full visibility.", color: "#f58220", emoji: "⚙️", image: "/assets/companies/tff/therabreath-production-room.jpg" },
    { id: "partnership", num: 4, title: "Partnership", tagline: "Build together.", color: "#6c5ce7", emoji: "🤝", image: "/assets/companies/therabreath/complete-rinse.jpg" },
  ],
  qaSections: [
    {
      pillar: "Resiliency",
      pillarShort: "Pillar 1",
      num: 1,
      color: "#008fd3",
      emoji: "🛡️",
      image: "/assets/companies/tff/facility.jpg",
      intro: "Supply security as you scale.",
      cards: [
        { num: 1, emoji: "📈", image: "/assets/companies/tff/facility.jpg", question: "If volume doubles in 3–5 years — how do we keep up?", hints: ["Built for headroom", "More shifts & equipment", "Invest as you grow"] },
        { num: 2, emoji: "🔗", image: "/assets/companies/tff/certifications.png", question: "What if a key supplier goes away?", hints: ["Secondary sources", "Critical inventory", "Lessons from PG shortage"] },
        { num: 3, emoji: "👥", image: "/assets/companies/tff/therabreath-production-room.jpg", question: "What if a key person is out?", hints: ["Cross-trained team", "No single point of failure", "Continuity by design"] },
        { num: 4, emoji: "✅", image: "/assets/companies/tff/certifications.png", question: "Quality at higher volume?", hints: ["Full traceability", "Batch records", "Same specs, more scale"] },
        { num: 5, emoji: "🆘", image: "/assets/companies/tff/facility.jpg", question: "Major disruption or disaster?", hints: ["Contingency plans", "Backup capacity", "Supply continuity"] },
      ],
    },
    {
      pillar: "Innovation",
      pillarShort: "Pillar 2",
      num: 2,
      color: "#5fb832",
      emoji: "💡",
      image: "/assets/portfolio/green-tea-fresh.jpg",
      intro: "What's next for flavor & oral care.",
      cards: [
        { num: 6, emoji: "🔭", image: "/assets/portfolio/watermelon-mojito.jpg", question: "How do you stay ahead of trends?", hints: ["We bring ideas to you", "Watch ingredients & consumers", "Proactive, not reactive"] },
        { num: 7, emoji: "🧃", image: "/assets/companies/therabreath/cat-gum-health.jpg", question: "Beyond mouthrinse?", hints: ["Kids · gummies · powders", "Wellness & seasonal", "Future adjacencies"] },
        { num: 8, emoji: "⚡", image: "/assets/portfolio/icy-peak-refresh.jpg", question: "How do you innovate?", hints: ["Fast prototypes", "Your feedback loop", "Bench → production"] },
        { num: 9, emoji: "👃", image: "/assets/qr/score.png", question: "How do you validate sensory?", hints: ["Triangle testing", "Consumer feedback", "University partners"] },
        { num: 10, emoji: "🚀", image: "/assets/portfolio/electric-blue-chill.jpg", question: "What excites you most for TheraBreath?", hints: ["Next-gen cooling", "Pediatric & wellness", "Seasonal & longevity"] },
      ],
    },
    {
      pillar: "Operations",
      pillarShort: "Pillar 3",
      num: 3,
      color: "#f58220",
      emoji: "⚙️",
      image: "/assets/companies/tff/therabreath-production-room.jpg",
      intro: "How we run day to day.",
      cards: [
        { num: 11, emoji: "🏗️", image: "/assets/companies/tff/therabreath-production-room.jpg", question: "What have you invested for TheraBreath?", hints: ["Dedicated TB space", "Warehouse & process", "Quality systems"] },
        { num: 12, emoji: "📦", image: "/assets/companies/tff/facility.jpg", question: "Service levels & lead times?", hints: ["Proactive scheduling", "Close collaboration", "Flexible + reliable"] },
        { num: 13, emoji: "🌿", image: "/assets/companies/tff/oral-care.png", question: "Securing critical raw materials?", hints: ["Supplier relationships", "Alt sourcing", "Inventory visibility"] },
      ],
    },
    {
      pillar: "Partnership",
      pillarShort: "Pillar 4",
      num: 4,
      color: "#6c5ce7",
      emoji: "🤝",
      image: "/assets/companies/therabreath/oxyd8-hero.jpg",
      intro: "Why us — and where we're headed.",
      cards: [
        { num: 14, emoji: "⭐", image: "/assets/companies/therabreath/dr-katz.png", question: "Why TFF long term?", hints: ["Responsive & flexible", "Technical depth", "We invest with you"] },
        { num: 15, emoji: "🎯", image: "/assets/companies/tff/oral-care.png", question: "What makes TFF different?", hints: ["Direct to leadership", "Fast decisions", "Trust & transparency"] },
        { num: 16, emoji: "🏆", image: "/assets/companies/therabreath/oxyd8-hero.jpg", question: "Success in 5 years?", hints: ["Shared growth", "Innovation pipeline", "Resilient partnership"] },
      ],
    },
  ],
  strategicQuestions: [
    { num: 1, emoji: "🎯", image: "/assets/companies/therabreath/oxyd8-hero.jpg", question: "What does success look like in 3–5 years?", hint: "Align our investments" },
    { num: 2, emoji: "🧗", image: "/assets/companies/therabreath/cat-bad-breath.png", question: "Biggest growth challenges?", hint: "Where we can help" },
    { num: 3, emoji: "🏅", image: "/assets/companies/tff/certifications.png", question: "What separates great suppliers?", hint: "Our roadmap" },
    { num: 4, emoji: "🛡️", image: "/assets/companies/tff/facility.jpg", question: "How can we support resiliency?", hint: "Your expectations" },
    { num: 5, emoji: "💡", image: "/assets/portfolio/cloud-matcha-mint.jpg", question: "Innovation opportunities that excite you?", hint: "Focus R&D" },
    { num: 6, emoji: "👀", image: "/assets/portfolio/y2k-bubblegum-mint.jpg", question: "Underappreciated oral care trends?", hint: "First-mover edge" },
    { num: 7, emoji: "👃", image: "/assets/portfolio/spearmint-garden.jpg", question: "Sensory attributes that matter now?", hint: "Flavor direction" },
    { num: 8, emoji: "💬", image: "/assets/companies/tff/oral-care.png", question: "How can TFF be a stronger partner?", hint: "Honest feedback" },
    { num: 9, emoji: "📊", image: "/assets/qr/score.png", question: "How should sensory data be presented?", hint: "Actionable format" },
    { num: 10, emoji: "✨", image: "/assets/companies/therabreath/complete-rinse.jpg", question: "What builds confidence after today?", hint: "Close remaining gaps" },
  ],
  chapters: null,
};